os: linux
dist: xenial
language: generic
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

# Download and unpack the stack executable
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# Build dependencies
install:
  - stack --no-terminal --install-ghc test --only-dependencies
  - stack install hpc-codecov

# Build the package, docs, and run tests
script:
  - stack --no-terminal build --test --pedantic --fast --coverage --haddock --no-haddock-deps
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint src/ app/

# Send code coverage report
after_script:
  - hpcroot=$(stack path --local-hpc-root)
  - tix=$(find $hpcroot -name 'test-main.tix')
  - mix=$(stack path --distdir)/hpc
  - hpc-codecov --mix=$mix --exclude=Paths_hpc_codecov -o codecov.json $tix
  - bash <(curl -s https://codecov.io/bash)
