codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "55...75"
  status:
    project:
      default:
        target: 75

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
