
--module FunctionState (addParameter,
--                      parameterPosition,
--                      parameterDeclared) where
--
--
--import qualified Data.Map as M
--
--import Evaluator (Evaluator(Ev))
--import Types (SymTab(funcStates), FuncState(..))
--import FrameStack (currentFunction)
--
--
--{- API -}
--
--
--
--{- Internal -}
--
