name:                succ
version:             0.1.0.0
github:              "jgthomas/succ"
license:             BSD3
author:              "James Thomas"
maintainer:          "jgtcode@protonmail.com"
copyright:           "2019 James Thomas"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jgthomas/succ#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- filepath
- process
- transformers
- mtl
- deepseq

library:
  source-dirs: src

executables:
  succ-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - succ

tests:
  succ-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - succ
    - hspec
